version: '3'
services:
  web:
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - D:/Project/boiduongtuvanluat:/var/www/html
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password